name: Lint

on:
  push:
    paths:
      - "**.py"
      - "**.pyi"
      - "pyproject.toml"
      - ".ruff.toml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - "**.pyi"
      - "pyproject.toml"
      - ".ruff.toml"
      - ".github/workflows/lint.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Lint with Ruff
        run: |
          # Using uvx to run ruff without installation
          uv --version
          uvx ruff@0.3.0 check .
      - name: Format with Ruff
        run: |
          # Using uvx to run ruff without installation
          uvx ruff@0.3.0 format --check .