name: Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e ".[dev]"
      - name: Type check with mypy
        run: |
          . .venv/bin/activate
          uv run mypy src tests